services:
  - type: web
    name: vocallocal
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y portaudio19-dev python3-pyaudio
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11 